### DISCUSSION TITLE
Setting up lvgl_micropython on the Sunton ESP32 3248S035C 3.5" capacitive touch 480x320 LCD board

### DISCUSSION THREAD

**Discussion by gitcnd** [lvgl-micropython/lvgl_micropython#282] [Board Specific]
Here is another working setup for another different kind of display.

Below is how I got the screen and touch working on my  ESP32 3248S035

### Build:-

`python3 make.py esp32 BOARD=ESP32_GENERIC BOARD_VARIANT=SPIRAM DISPLAY=st7796 INDEV=gt911`

## (Optional) backup your flash before overwriting it:

`
export PORT=/dev/ttyS6
esptool.py --port $PORT read_flash 0x0 0x400000 lcd_3.5inch_ESP32-3248S035C.bin
`

### Flash:-

`esptool.py --port $PORT write_flash 0x0 lvgl_micropy_ESP32_GENERIC-SPIRAM-4.bin`

### Upload a test:-

`ampy --port $PORT put lvgl_test_3248S035C.py`

### Run it:-

``` bash
mcu_serial.pl -port $PORT
import lvgl_test_3248S035C
```

### The test program:
``` python
#WORKS lvgl_test_3248S035C.py

import lcd_bus
from micropython import const
import machine
from i2c import I2C

# display settings
_WIDTH  = const(320)
_HEIGHT = const(480)
_BL     = const(27)  # Backlight pin
_RST    = const(17)  # Reset - use -1 if you have none
_DC     = const(2)

_MOSI = const(13)
_MISO = const(12)
_SCK  = const(14)
_HOST = const(1)  # SPI2

_LCD_CS = const(15)
_LCD_FREQ = const(24000000)

spi_bus = machine.SPI.Bus(
    host=_HOST,
    mosi=_MOSI,
    miso=_MISO,
    sck=_SCK
)

display_bus = lcd_bus.SPIBus(
    spi_bus=spi_bus,
    freq=_LCD_FREQ,
    dc=_DC,
    cs=_LCD_CS,
)


import st7796  
import lvgl as lv 

display = st7796.ST7796(
    data_bus=display_bus,
    display_width=_WIDTH,
    display_height=_HEIGHT,
    backlight_pin=_BL,
    backlight_on_state=st7796.STATE_PWM,
    color_space=lv.COLOR_FORMAT.RGB565,
    color_byte_order=st7796.BYTE_ORDER_BGR,
    rgb565_byte_swap=True
)

import task_handler

import gt911

I2C_BUS = I2C.Bus(
    host=0,
    scl=32,
    sda=33,
    freq=400000,
    use_locks=False
)

TOUCH_DEVICE = I2C.Device(
    I2C_BUS,
    dev_id=gt911.I2C_ADDR,
    reg_bits=gt911.BITS
)

display.set_power(True)
display.init()
display.set_backlight(100)
indev = gt911.GT911(TOUCH_DEVICE)


th = task_handler.TaskHandler()

scrn = lv.screen_active()
scrn.set_style_bg_color(lv.color_hex(0x000000), 0)

slider = lv.slider(scrn)
slider.set_size(300, 50)
slider.center()

main_label = lv.label(scrn)
main_label.set_text('HELLO WORLD!')
main_label.align(lv.ALIGN.CENTER, 0, -50)

# Add R G and B colour checks
r_label = lv.label(scrn)
r_label.set_text('R')
r_label.set_style_text_color(lv.color_hex(0xFF0000), 0)
r_label.align_to(main_label, lv.ALIGN.OUT_TOP_LEFT, -20, -10)

g_label = lv.label(scrn)
g_label.set_text('G')
g_label.set_style_text_color(lv.color_hex(0x00FF00), 0)
g_label.align_to(main_label, lv.ALIGN.OUT_TOP_MID, 0, -10)

b_label = lv.label(scrn)
b_label.set_text('B')
b_label.set_style_text_color(lv.color_hex(0x0000FF), 0)
b_label.align_to(main_label, lv.ALIGN.OUT_TOP_RIGHT, 20, -10)
```

### Screenshots:-
![IMG_20250204_015244_765](https://github.com/user-attachments/assets/0e5e2248-97b8-4865-83e6-87a0e3bca290)
![IMG_20250204_015308_726](https://github.com/user-attachments/assets/17d732b3-4357-4d60-ab75-a4f3acfb91bf)

**Comment by kdschlosser** [comment]
Might I make a suggestion for ya..

Create specific "board" setup files using TOML. There is an example in the root directory that shows how it is done. If you have any questions I would be more than happy to help you out with it. The TOML files are written so it will provide all of the build commands and it will write the driver code and bake the driver code into the firmware as a model named "display"

**Reply by gitcnd** [reply]
Excellent idea.  My main goal for all these discussion-postings is to give other people who, like me, are perpetually "Stuck" with these boards, something they can find and do to get the things "just working".  I bought "one of every kind" a year or so ago, and I'm working through them all.  
I have not yet added wifi and SD-card and ambient-light-sensing and LED control and speaker usage into my tests, but I'm hoping to manage that as well.

I wrote a compact read/write toml libarary for micropython already: https://github.com/gitcnd/toml
As well as a linux-style bash shell emulation: https://github.com/gitcnd/mpy_shell
And a telnet daemon for the REPL: https://github.com/gitcnd/telnetd (blows me away how fast esp32 is when not stuck on 115200 serial!)
And msgpack: https://github.com/gitcnd/micropython-msgpack
And uudecode (in an attempt to make file transfers easier) https://github.com/gitcnd/uudecode
And sz/rz https://github.com/gitcnd/mrzsz
And an incredible espnow module which does secure (with anti-replay) broadcasts: https://github.com/gitcnd/nowcom

The [mpy_shell](https://github.com/gitcnd/mpy_shell) has the (two-way) "curl" command, and I added a "backup" command which sends every file on your flash to your own web server (using curl) - again - blows me away with its speed. Entire flash saved to a remote server in a few seconds.

I'm wanting to write some kind of "bootstrap" - code which can be flashed to a new board, which when run makes it a no-brainer for the user to connect it to their wifi without having to fuss around with changing files (either using the screen, or their phone to connect to the device's hotspot).  I've done this 3 or 4 times so far, and it always gets more complicated than I expected (e.g. needing both a hotspot, as well as a wifi connection, with the ability to fall back to other wifis in a priority order, all without degrading how espnow needs to work with it's channel dependencies...)

If my "real work" doesn't get in the way, my goal with all this is to put some demo's here of how to make these boards "fully functional" (hopefully including a touchscreen-enabled "REPL" running my bash-like shell...)

**Reply by kdschlosser** [reply]
The toml file is parsed by the builder and the builder then generates a py file with the display drivers and it bakes that file into the firmware. This is a really nice feature to have because it enables user to share the files for specific display/mcu boards. You can also add into the toml file the build commands that are specific to a board. so all that needs to be done to compile is `python3 make.py --toml=/absolute/path/to/board.toml` and it is off and running. Once the board boots all the user has to do is do an `import display` and that will get the display and the touch input (if supplied) up and running.

The parsing script is pretty intelligent in how I designed it. so it is able to tell if an import needs to be added and how to store things with respect to variable names.


if we look at the example..

```toml

[MCU.esp32]
BOARD = "ESP32_GENERIC_S3"
BOARD_VARIANT = "SPIRAM_OCT"
octal_flash = true
flash_size = 16
enable_jtag_repl = 'n'
enable_cdc_repl = 'n'
enable_uart_repl = 'y'
uart_repl_bitrate = 115200



[I80Bus.display_bus]
data0 = 9
data1 = 46
data2 = 3
data3 = 8
data4 = 18
data5 = 17
data6 = 16
data7 = 15
dc = 0
wr = 47
cs = -1
freq = 20000000


[I2C.Bus.i2c_bus]
host = 0
scl = 5
sda = 6
freq = 100000


[I2C.Device.indev_device]
bus = "i2c_bus"
dev_id = "ft6x36.I2C_ADDR"
reg_bits = "ft6x36.BITS"


[ST7796.display]
data_bus = "display_bus"
display_width = 320
display_height = 480
backlight_pin = 45
color_byte_order = "st7789.BYTE_ORDER_BGR"
color_space = "lv.COLOR_FORMAT.RGB565"
rgb565_byte_swap = true

[display.init]
params = []

[FT6x36.indev]
device = "indev_device"

[display.set_color_inversion]
params = [true]

[display.set_rotation]
params = ["lv.DISPLAY_ROTATION._90"]

[display.set_backlight]
params = [100]

[task_handler.TaskHandler]
params=[]

```

the build command section

```toml

[MCU.esp32]
BOARD = "ESP32_GENERIC_S3"
BOARD_VARIANT = "SPIRAM_OCT"
octal_flash = true
flash_size = 16
enable_jtag_repl = 'n'
enable_cdc_repl = 'n'
enable_uart_repl = 'y'
uart_repl_bitrate = 115200
```

is pretty self explanatory. The only thing that has a catch is build commands that do not have a value to them like `--octal-flash` and those when set in the toml file should always be set to have a value of `true`


when dealing with display drivers and bus drivers you have the following at the top. `[I80Bus.display_bus]` This breaks down into `[class name.variable name]`. 

if we want to call a method of an instance it is done as follows.
```toml
[display.set_rotation]
params = ["lv.DISPLAY_ROTATION._90"]
```

**Reply by kdschlosser** [reply]
I am going to create a subfolder that I can place these toml files into so people are able to use them to get up and running faster.

**Reply by gitcnd** [reply]
Incredibly cool.  Next one I do I'll try that.  
Is (or can) the toml itself be backed into the firmware somehow (so user python scripts can read it)?  It would be nice if others could add to that file (e.g. ambient-light sensor, LED/neopixel settings/pins, speaker, IMU, SD, ...) and subsequent code shared among different boards could properly find and use that stuff inside the python...
(It would also be very handy if you had a firmware binary, and wanted to extract the settings out of it...)

Here's one random .toml file of my own for one of my boards (showing, in the comments, different settings for a bunch of other boards)

``` toml
HW = { "BOARD":    "cydv3",     # S2_MINI       C3_SUPERMINI    S3_MINI         CYB28R          C6 Momo         ESP32_CAM       CYB24C          CYB28R
       "LED":      16,          # 15            8               -47 (neopixel)  4=r 16=g 17=b   8               4 (flashlight)  4=R 16=G 17=B   16=g 17=b (noR)
       "LEDINV":   1,           # 0             1               0               0               0               0               1               1
       "LEDCOL":   "GRN",       # 0             1               0               0               0               0               1               1
       "LED2":     17,
       "LED2INV":  1,
       "LED2COL":  "BLU",
       "LCD":      "st7789",
       "LCD_CLASS": "ST7789",
       "LCD_DRIVER":"st7789cnd",
       "LCD_WIDTH": 240,
       "LCD_HEIGHT":320,
       "LCD_BAUD":  40000000, # HSPI
       "LCD_SCK":   14,
       "LCD_MOSI":  13,
       "LCD_MISO":  12,
       "LCD_RESET": 0,
       "LCD_CS":    15,
       "LCD_DC":    2,
       "LCD_BACKLIGHT": 21,
       "LCD_ROTATION": 0,
       "TOUCH":    "xpt2046",
       "TOUCH_DRV":"xpt2046", # this has my rotation feature added
       "TOUCH_BAUD":  500000,
       "TOUCH_SCK": 25,
       "TOUCH_MOSI":32,
       "TOUCH_MISO":39,
       "TOUCH_CS":  33,
       "TOUCH_IRQ": 36,
       "I2C1_SCL":  18,
       "I2C1_SDA":  19,
       "MPU6050":   1, # I2C bus#
       "MPU6050_ADDR": 104,
       "MPU6050_DRV": "mpu6050",
       "BMP180":    1, # I2C bus
       "BMP180_ADDR":  119,
       "BMP180_DRV": "bmp085",
       "QMC5883":   1, # I2C bus
       "QMC5883_ADDR":   13,
       "QMC5883_DRV": "qmc5883L",
       "SD":       "VSPI",
       "SD_SS":     5,
       "SD_SCK":    6,
       "SD_SD0":    7,
       "SD_SD1":    8,
       "SD_SD2":    9,
       "SD_SD3":    10,
       "SD_CMD":    11,
       "SD_CMD":    11,
       "SD_SCK":    18,
       "SD_MISO":   19,
       "SD_MOSI":   23,
       "SPEAKER":   26,
       "LIGHT_SENSE":   34
      }
```

**Comment by gitcnd** [comment]
Hmm. The .toml build fails?  It seems to be looking for a build_command section?:

```
[cdc:/lvgl]$ python3 make.py --toml=/lvgl/custom_board_and_toml_examples/esp32_8048S043/esp32_8048S043.toml
Traceback (most recent call last):
  File "/lvgl/builder/toml_reader.py", line 265, in run
    build_command = toml_obj.build_command
  File "/lvgl/builder/toml_reader.py", line 67, in __getattr__
    raise AttributeError(item)
AttributeError: build_command

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/lvgl/make.py", line 62, in <module>
    build_command = toml_reader.run(toml_path, driver_out_path)
  File "/lvgl/builder/toml_reader.py", line 284, in run
    raise SyntaxError(f'Unable to parse .toml file ({toml_path}) e={err}') from err
SyntaxError: Unable to parse .toml file (/lvgl/custom_board_and_toml_examples/esp32_8048S043/esp32_8048S043.toml) e=build_command
```

make.py line 62:
`        build_command = toml_reader.run(toml_path, driver_out_path)`

I don't see that mentioned in the [doc](https://github.com/lvgl-micropython/lvgl_micropython/tree/main/custom_board_and_toml_examples/toml_example)?

I was attempting to see if this new build idea might fix my [i2c issue](https://github.com/lvgl-micropython/lvgl_micropython/issues/285)...

[devnull@cdc: Err:1/lvgl]$ cat  custom_board_and_toml_examples/esp32_8048S043/esp32_8048S043.toml  
```
[MCU.esp32]
BOARD = "ESP32_GENERIC_S3"
BOARD_VARIANT = "SPIRAM_OCT"
octal_flash = true
flash_size = 8
enable_jtag_repl = "n"
enable_cdc_repl = "n"
enable_uart_repl = "y"
uart_repl_bitrate = 115200

[I80Bus.display_bus]
data0 = 8
data1 = 3
data2 = 46
data3 = 9
data4 = 1
data5 = 5
data6 = 6
data7 = 7
data8 = 15
data9 = 16
data10 = 4
data11 = 45
data12 = 48
data13 = 47
data14 = 21
data15 = 14
freq = 12000000
hsync = 39
vsync = 41
de = 40 
pclk = 42
hsync_front_porch = 8
hsync_back_porch = 8
hsync_pulse_width = 4
hsync_idle_low = true
vsync_front_porch = 8
vsync_back_porch = 8
vsync_pulse_width = 4
vsync_idle_low = true
de_idle_high = false
pclk_idle_high = false
pclk_active_low = true

[I2C.Bus.i2c_bus]
host = 0
scl = 19
sda = 20
freq = 400000

[I2C.Device.indev_device]
bus = "i2c_bus"
dev_id = "gt911.I2C_ADDR"
reg_bits = "gt911.BITS"

[rgb_display.display]
data_bus = "display_bus"
display_width = 800
display_height = 480
backlight_pin = 2
color_byte_order = "rgb_display.BYTE_ORDER_BGR"
color_space = "lv.COLOR_FORMAT.RGB565"

[rgb_display.display.init]
params = []

[GT911.indev]
device = "indev_device"

[display.set_color_inversion]
params = [true]

[display.set_rotation]
params = ["lv.DISPLAY_ROTATION._90"]

[display.set_backlight]
params = [100]

[task_handler.TaskHandler]
params=[]
```

**Reply by kdschlosser** [reply]
Your toml file is wrong.

It should be...

```toml
[MCU.esp32]
BOARD = "ESP32_GENERIC_S3"
BOARD_VARIANT = "SPIRAM_OCT"
octal_flash = true
flash_size = 8
enable_jtag_repl = "n"
enable_cdc_repl = "n"
enable_uart_repl = "y"
uart_repl_bitrate = 115200

[I80Bus.display_bus]
data0 = 8
data1 = 3
data2 = 46
data3 = 9
data4 = 1
data5 = 5
data6 = 6
data7 = 7
data8 = 15
data9 = 16
data10 = 4
data11 = 45
data12 = 48
data13 = 47
data14 = 21
data15 = 14
freq = 12000000
hsync = 39
vsync = 41
de = 40 
pclk = 42
hsync_front_porch = 8
hsync_back_porch = 8
hsync_pulse_width = 4
hsync_idle_low = true
vsync_front_porch = 8
vsync_back_porch = 8
vsync_pulse_width = 4
vsync_idle_low = true
de_idle_high = false
pclk_idle_high = false
pclk_active_low = true

[I2C.Bus.i2c_bus]
host = 0
scl = 19
sda = 20
freq = 400000

[I2C.Device.indev_device]
bus = "i2c_bus"
dev_id = "gt911.I2C_ADDR"
reg_bits = "gt911.BITS"

[RGBDisplay.display]
data_bus = "display_bus"
display_width = 800
display_height = 480
backlight_pin = 2
color_space = "lv.COLOR_FORMAT.RGB565"

[display.init]
params = []

[GT911.indev]
device = "indev_device"

[display.set_color_inversion]
params = [true]

[display.set_rotation]
params = ["lv.DISPLAY_ROTATION._90"]

[display.set_backlight]
params = [100]

[task_handler.TaskHandler]
params=[]
```

The `color_byte_order` doesn't do anything for RGB displays. It is there to keep the API more consistent between the drivers. 

I just updated the toml reading script. It should be working now.
