### DISCUSSION TITLE
Setting up lvgl_micropython on the Sunton ESP32 8048S043C 4.3" capacitive touch 800x480 LCD board

### DISCUSSION THREAD

**Discussion by gitcnd** [lvgl-micropython/lvgl_micropython#287] [Board Specific]
Here is another working setup for another different kind of display.

Below is how I got the screen and touch working on my  ESP32 8048S043

### Note:-

This board uses GPIO pins 19 and 20 for the touch controller, which micropython reserves for JTAG - so you need to use the `--enable-cdc-repl=n --enable-jtag-repl=n` options during the build:

### Build:-

` python3 make.py esp32 BOARD=ESP32_GENERIC_S3 BOARD_VARIANT=SPIRAM_OCT DISPLAY=rgb_display INDEV=GT911 --enable-cdc-repl=n --enable-jtag-repl=n`

## (Optional) backup your flash before overwriting it:

`
export PORT=/dev/ttyS6
esptool.py --port $PORT read_flash 0x0 0x400000 lcd_3.5inch_ESP32-8048S043C.bin
`

### Flash:-

`esptool.py --port $PORT write_flash 0x0 lvgl_micropy_ESP32_GENERIC_S3-SPIRAM_OCT-8.bin`

### Upload a test:-

`ampy --port $PORT put lvgl_test_8048S043C.py`

### Run it:-

``` bash
mcu_serial.pl -port $PORT
import lvgl_test_8048S043C
```

### The test program:
``` python
# lvgl_test_8048S043C.py

import micropython
micropython.mem_info()

import lcd_bus

display_bus = lcd_bus.RGBBus(
    hsync = 39,
    vsync = 41,
    de = 40,
    pclk = 42,  # to TFT DCLK
    data0  = 8,  data1  = 3,  data2  = 46, data3  = 9,  data4  = 1,  # B
    data5  = 5,  data6  = 6,  data7  = 7,  data8  = 15, data9  = 16, data10 = 4,  # G
    data11 = 45, data12 = 48, data13 = 47, data14 = 21, data15 = 14,  # R
    freq = 12000000,
    hsync_front_porch = 8,
    hsync_back_porch = 8,
    hsync_pulse_width = 4,
    hsync_idle_low = True,
    vsync_front_porch = 8,
    vsync_back_porch = 8,
    vsync_pulse_width = 4,
    vsync_idle_low = True,
    de_idle_high = False,
    pclk_idle_high = False,
    pclk_active_low = True,
)

import rgb_display
import lvgl as lv
display = rgb_display.RGBDisplay(
    data_bus = display_bus,
    display_width = 800,
    display_height = 480,
    backlight_pin = 2,
    color_byte_order = rgb_display.BYTE_ORDER_BGR,
    color_space = lv.COLOR_FORMAT.RGB565,
)

display.init()
display.set_backlight(100)

from i2c import I2C

import task_handler

import gt911
from micropython import const

_WIDTH = const(800)
_HEIGHT = const(480)


I2C_BUS = I2C.Bus(
    host=0,
    scl=20,
    sda=19,
    freq=400000,
    use_locks=False
)

TOUCH_DEVICE = I2C.Device(
    I2C_BUS,
    dev_id=gt911.I2C_ADDR,
    reg_bits=gt911.BITS
)

display.set_power(True)
display.init()
display.set_backlight(100)

indev = gt911.GT911(TOUCH_DEVICE)

if indev.hw_size != (_WIDTH, _HEIGHT):
    fw_config = indev.firmware_config
    fw_config.width = _WIDTH
    fw_config.height = _HEIGHT
    fw_config.save()

th = task_handler.TaskHandler()

scrn = lv.screen_active()
scrn.set_style_bg_color(lv.color_hex(0x000000), 0)

slider = lv.slider(scrn)
slider.set_size(300, 50)
slider.center()

main_label = lv.label(scrn)
main_label.set_text('HELLO WORLD!')
main_label.align(lv.ALIGN.CENTER, 0, -50)

# Add R G and B colour checks
r_label = lv.label(scrn)
r_label.set_text('R')
r_label.set_style_text_color(lv.color_hex(0xFF0000), 0)
r_label.align_to(main_label, lv.ALIGN.OUT_TOP_LEFT, -20, -10)

g_label = lv.label(scrn)
g_label.set_text('G')
g_label.set_style_text_color(lv.color_hex(0x00FF00), 0)
g_label.align_to(main_label, lv.ALIGN.OUT_TOP_MID, 0, -10)

b_label = lv.label(scrn)
b_label.set_text('B')
b_label.set_style_text_color(lv.color_hex(0x0000FF), 0)
b_label.align_to(main_label, lv.ALIGN.OUT_TOP_RIGHT, 20, -10)
```

### Screenshots:-
![IMG_20250205_174938_121](https://github.com/user-attachments/assets/0b45dd76-a016-4c76-8e9e-56a5c1eeca2a)
![IMG_20250205_174957_592](https://github.com/user-attachments/assets/c88580bc-58e8-4142-b4fd-c9425030bb3e)

### Prebuilt working .bin :-) :-
`LVGL (9.2.2) MicroPython (1.24.1) Binding compiled on 2025-02-05; Generic ESP32S3 module with Octal-SPIRAM with ESP32S3`
[lvgl_micropy_ESP32_GENERIC_S3-SPIRAM_OCT-8-Sunton-8048S043C.zip](https://github.com/user-attachments/files/18668514/lvgl_micropy_ESP32_GENERIC_S3-SPIRAM_OCT-8-Sunton-8048S043C.zip)

flash as follows:-
```
export PORT=/dev/ttyS6
esptool.py --port $PORT erase_region 0x200000 0x200000 # clear spiffs first
esptool.py --port $PORT write_flash 0x0 lvgl_micropy_ESP32_GENERIC_S3-SPIRAM_OCT-8-Sunton-8048S043C.bin
```

### Future:-
If I work out how to use the new .toml build system in future, I'll come back and amend this discussion.

### Note:
This discussion post has been updated. The original post included instructions for changing files, which the `--enable-cdc-repl=n` and `--enable-jtag-repl=n` options mitigate the need for.
I plan to again update this discussion when the new .toml build process is tested and working.

**Comment by kdschlosser** [comment]
You do not need to make those changes to MicroPython in order to get the touch to work. That is what the `--enable-cdc-repl`, `--enable-jtag-repl` and `--enable-uart-repl` do. There is no need to modify any of the file in MicroPython. I advise against doing that. It is better to define a custom board and use the `--custom-board={path to custom board directory}` build command...

**Reply by gitcnd** [reply]
None of those switches made any difference - I spent all day debugging the missing gt911 on my I2C, and forcing the mpconfigport.h was the only thing that worked.

I'll try the .toml approach again on my next board - the examples left me scratching my head quite a lot - there's a pile of extra files in the example folder https://github.com/lvgl-micropython/lvgl_micropython/tree/main/custom_board_and_toml_examples/MY_CUSTOM_BOARD 
but I assume I can just ignore all those?

**Reply by kdschlosser** [reply]
trust me when I say it works Others have used them and had it fix the EXACT same issue. The reason why it is more than likely not working for you is because you have changed something in MicroPython that is specifically looked for and it is no longer there so it cannot set things correctly.

You can see right [here](https://github.com/lvgl-micropython/lvgl_micropython/blob/b493626fc34276ac79349a202871cfc7cd0bd9d6/builder/esp32.py#L1066) what is taking place with the build script.



The example is located [here](https://github.com/lvgl-micropython/lvgl_micropython/blob/main/custom_board_and_toml_examples/toml_example/example_build_toml.toml)

**Reply by gitcnd** [reply]
I fired up a fresh ubuntu, did a new "git clone" and this does now build a working binary:

`python3 make.py esp32 BOARD=ESP32_GENERIC_S3 BOARD_VARIANT=SPIRAM_OCT DISPLAY=rgb_display INDEV=GT911 --enable-cdc-repl=n --enable-jtag-repl=n 
`
(I had not changed anything on the other build, but it was on a centos machine).

This, however (in my new fresh ubuntu), 
```
python3 make.py --toml=/dl/lm/custom_board_and_toml_examples/esp32_8048S070C.toml 
python3 make.py --toml=/dl/lm/custom_board_and_toml_examples/esp32_8048S070C.toml 
```
(yes - have to run it twice, because the first run always fails immediately with an options error)
builds a binary which does not boot (gets stuck in a reset loop at the start.  Looking at the `hexdump -C` of the broken and working start of both binaries, they seem mostly the same (different build time, otherwise the same):

First one crashes. Second one works.
```
2513872 2025-02-05 20:48  lvgl_micropy_ESP32_GENERIC_S3-SPIRAM_OCT-8_OCTFLASH-esp32_8048S070C-toml.bin
2516544 2025-02-05 21:36  lvgl_micropy_ESP32_GENERIC_S3-SPIRAM_OCT-8-rgb_display-gt911-esp32_8048S070rebuild.bin
```


cat /dl/lm/custom_board_and_toml_examples/esp32_8048S070C.toml 
``` toml
[MCU.esp32]
BOARD = "ESP32_GENERIC_S3"
BOARD_VARIANT = "SPIRAM_OCT"
octal_flash = true
flash_size = 8
enable_jtag_repl = "n"
enable_cdc_repl = "n"
enable_uart_repl = "y"
uart_repl_bitrate = 115200

[I80Bus.display_bus]
data0 = 15
data1 = 7
data2 = 6
data3 = 5
data4 = 4
data5 = 9
data6 = 46
data7 = 3
data8 = 8
data9 = 16
data10 = 1
data11 = 14
data12 = 21
data13 = 47
data14 = 48
data15 = 45
freq = 12000000
hsync = 39
vsync = 40
de = 41 
pclk = 42
hsync_front_porch = 210
hsync_back_porch = 16
hsync_pulse_width = 30
hsync_idle_low = true
vsync_front_porch = 22
vsync_back_porch = 10
vsync_pulse_width = 13
vsync_idle_low = true
de_idle_high = false
pclk_idle_high = false
pclk_active_low = true

[I2C.Bus.i2c_bus]
host = 0
scl = 19
sda = 20
freq = 400000

[I2C.Device.indev_device]
bus = "i2c_bus"
dev_id = "gt911.I2C_ADDR"
reg_bits = "gt911.BITS"

[RGBDisplay.display]
data_bus = "display_bus"
display_width = 800
display_height = 480
backlight_pin = 2
color_space = "lv.COLOR_FORMAT.RGB565"

[display.init]
params = []

[GT911.indev]
device = "indev_device"

[display.set_color_inversion]
params = [true]

[display.set_rotation]
params = ["lv.DISPLAY_ROTATION._90"]

[display.set_backlight]
params = [100]

[task_handler.TaskHandler]
params=[]
```
